//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace businesslogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout_collections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workout_collections()
        {
            this.Workout_Activss = new HashSet<Workout_Activss>();
        }
    
        public string workout_title { get; set; }
        public string workout_note { get; set; }
        public Nullable<double> calories_burn_per_minute { get; set; }
        public Nullable<int> category_id { get; set; }
        public int workout_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workout_Activss> Workout_Activss { get; set; }
        public virtual workout_categorys workout_categorys { get; set; }
    }
}
